    </main>

    <footer>
        <p><small>Autor: <strong>Kamil Drzazga</strong>.</small></p>
        <p><small>Projekt nr <strong>2</strong> na Techniki Internetowe.</small></p>
    </footer>

    <ul class="stick-to-top-right-corner menu">
        <li class="dropdown">
            <?php if (!isset($_SESSION["logged"])): ?>
                <a class="icon-user" href="javascript:void(0);">Niezalogowany</a>
                <div class="dropdown-body">
                    <p>Musisz się zalogować, by korzystać z aplikacji!</p>
                    <p><a href="/?controller=auth&action=register">Rejestracja</a></p>
                    <p><a href="/?controller=auth&action=login">Logowanie</a></p>
                </div>
            <?php else: ?>
                <a class="icon-user" href="javascript:void(0);">Zalogowany</a>
                <div class="dropdown-body">
                    <p>Zalogowano jako <em><?= $_SESSION["logged"] ?></em></p>
                    <p><a href="/?controller=auth&action=logout">Wylogowanie</a></p>
                </div>
            <?php endif; ?>
        </li>
    </ul>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <?php foreach ($scripts as $script): ?>
        <script src="/assets/js/<?= $script ?>.js"></script>
    <?php endforeach; ?>

</body>
</html>