<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <title><?= $title ?></title>
    <link href="/assets/css/fontello.css" rel="stylesheet" />
    <link href="/assets/css/style.css" rel="stylesheet" />
</head>
<body>

    <header>
        <h1>Web<em>J</em></h1>
        <h2><?= $description ?></h2>
    </header>

    <nav>
        <ul class="menu">
            <li><a href="/">Strona główna</a></li>
            <li><a href="/?controller=song&action=show-all">Mixer</a></li>
            <li><a href="/?controller=usage">Jak używać</a></li>
            <li><a href="/?controller=docs">Dokumentacja</a></li>
        </ul>
    </nav>

    <main>
        <?php if (isset($_SESSION["message"])): ?>
            <p class="message
            <?php
                if (isset($_SESSION["message-class"]))
                    echo $_SESSION["message-class"];
            ?>
            "><?= $_SESSION["message"] ?></p>
        <?php endif; ?>