<section>
    <h3>Klient - JavaScript</h3>
    <p>Aplikacja po stronie klienta składa się z plików <code>js</code>.</p>
    <p>Podkatalog: assets/js/</p>
    <ul>
        <li>Audio.js - zawiera obiekt Audio na podstawie którego można tworzyć obiekty które reprezentują pojedyńczy utwór do przeciągnięcia na linię czasową</li>
        <li>Sample.js - jest tam obiekt Sample, który reprezentuje przeciągnięty utwór na track</li>
        <li>Track.js - zawiera obiekt Track na podstawie którego można utworzyć nową linię czasową</li>
        <li>Mixer.js - jest tam obiekt spajający wszystkie elementy miksera w całość</li>
        <li>Storage.js- zarządza połączeniem serwerem i local storage. Wykrywanie jest tam np. czy aplikacja jest online, wysyła żądania AJAX do serwera</li>
    </ul>
</section>
<section>
    <h3>Server - PHP + sqLite3</h3>
    <p>Użyto wzorca MVC. Stworzono abstrakcję w dostępie do bazy danych (klasa abstrakcyjna Model). Wykorzystano też klasę Template, która dostarcza narzędzia do przekształcania szablonów (plików .phtml w katalogu templates) na konkretny kod html.</p>
    <p>Na początku programu uruchamia się obiekt klasy Loader i rejestruje funkcje autoładujące klasy poleceniem <code>spl_autoloader_register</code>. Później przy użyciu klasy Router pobierane są z adresu (metoda GET) 3 elementy:</p>
    <ul>
        <li>controller - czyli nazwa klasy (kontroler), która ma być utworzona</li>
        <li>action - czyli jaka metoda ma być wywołana</li>
        <li>params - dodatkowe parametry np. id utworu</li>
    </ul>
    <p>Dzięki poprzednim operacją wiadomo jest jaką klasę należy utworzyć i jaką metodę wywołać by obsłużyć żądanie.</p>
    <p>Diagram klas</p>
    <p><img src="/assets/img/php_class_diagram.png" alt="diagram klas php" /></p>
    <p>Diagram bazy danych</p>
    <p><img src="/assets/img/db_diagram.png" alt="diagram bazy danych" /></p>
</section>
<section>
    <h3>SOX - Sound eXchange</h3>
    <p>Program sox, który zainstalowany jest na serwerze, pozwala wygnerować gotowy plik audio z utworem.</p>
    <p>Link do projektu: <a href="http://sox.sourceforge.net/">http://sox.sourceforge.net/</a></p>
</section>