<section>
    <h3>Mixer</h3>
    <div id="tracks" class="grid">
        <aside class="grid-item"></aside>
        <div class="grid-iteme">
            <div class="scrollable">
                <div class="timelines"></div>
            </div>
        </div>
    </div>
    <button id="new-track">Dodaj ścieżkę</button>
</section>
<section>
    <h3>Dostępna muzyka</h3>
    <div id="audios"></div>
</section>