<section>
    <h3>Dostępne utwory</h3>
    <?php if (count($songs) > 0): ?>
        <ul class="deletable-list">
            <?php foreach ($songs as $song): ?>
                <li>
                    <a class="icon-cancel deleter" href="/?controller=song&action=delete&id=<?= $song["id"] ?>">Usuń</a>
                    <a href="/?controller=song&action=mix&id=<?= $song["id"] ?>">(ID#<?= $song["id"] ?>), <?= $song["name"] ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <p>Brak utworów</p>
    <?php endif; ?>
    <a href="/?controller=song&action=create"><button class="icon-plus">Dodaj nowy utwór</button></a>
</section>